import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 *
 * - Create an ordered group of docs
 * - Render a sidebar for each doc of that group
 * - Provide next/previous navigation
 *
 * The sidebars can be generated from the filesystem, or explicitly defined
 * here.
 *
 * Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
    docsSidebar: [
        {
            className: "sb-doc-overview",
            id: "index",
            label: "🏁 Overview",
            type: "doc",
        },
        {
            className: "sb-cat-getting-started",
            collapsed: false,
            customProps: { badge: "start" },
            items: [
                "getting-started/installation",
                "getting-started/quick-start",
                "getting-started/system-requirements",
            ],
            label: "🚀 Getting Started",
            link: {
                description: "Get up and running with FitFileViewer quickly.",
                title: "Getting Started",
                type: "generated-index",
            },
            type: "category",
        },
        {
            className: "sb-cat-user-guide",
            collapsed: true,
            customProps: { badge: "guide" },
            items: [
                "user-guide/opening-files",
                "user-guide/interface",
                "user-guide/data-visualization",
                "user-guide/export-sharing",
                "user-guide/keyboard-shortcuts",
                "user-guide/troubleshooting",
            ],
            label: "👤 User Guide",
            link: {
                description: "Comprehensive guide to using FitFileViewer.",
                title: "User Guide",
                type: "generated-index",
            },
            type: "category",
        },
        {
            className: "sb-cat-visualization",
            collapsed: true,
            customProps: { badge: "visual" },
            items: [
                "visualization/maps",
                "visualization/charts",
                "visualization/tables",
                "visualization/summary",
            ],
            label: "📊 Data Visualization",
            link: {
                description: "Interactive maps, charts, tables, and summary views.",
                title: "Data Visualization",
                type: "generated-index",
            },
            type: "category",
        },
        {
            className: "sb-cat-architecture",
            collapsed: true,
            customProps: { badge: "api" },
            items: [
                "architecture/overview",
                "architecture/process-model",
                "architecture/module-system",
                "architecture/data-flow",
                "architecture/security",
            ],
            label: "🏗️ Architecture",
            link: {
                description: "Technical architecture, design patterns, and internal workings.",
                title: "Architecture",
                type: "generated-index",
            },
            type: "category",
        },
        {
            className: "sb-cat-development",
            collapsed: true,
            customProps: { badge: "dev" },
            items: [
                "development/setup",
                "development/code-standards",
                "development/module-development",
                "development/testing",
                "development/build-release",
            ],
            label: "🛠️ Development",
            link: {
                description: "Development setup, standards, and contribution guidelines.",
                title: "Development",
                type: "generated-index",
            },
            type: "category",
        },
        {
            className: "sb-cat-api",
            collapsed: true,
            customProps: { badge: "api" },
            items: [
                "api-reference/core-apis",
                "api-reference/utility-apis",
                "api-reference/ipc-communication",
                "api-reference/state-management",
                {
                    label: "📚 Generated API Docs",
                    type: "category",
                    items: [
                        {
                            type: "autogenerated",
                            dirName: "api",
                        },
                    ],
                },
            ],
            label: "🔧 API Reference",
            link: {
                description: "API documentation for FitFileViewer modules and utilities.",
                title: "API Reference",
                type: "generated-index",
            },
            type: "category",
        },
        {
            className: "sb-cat-advanced",
            collapsed: true,
            customProps: { badge: "advanced" },
            items: [
                "advanced/performance",
                "advanced/state-management-deep-dive",
                "advanced/fit-parser-migration",
            ],
            label: "🧪 Advanced Topics",
            link: {
                description: "Deep dives into advanced topics and internals.",
                title: "Advanced Topics",
                type: "generated-index",
            },
            type: "category",
        },
        {
            className: "sb-cat-blog",
            collapsed: true,
            customProps: { badge: "blog" },
            items: [
                {
                        href: "/blog",
                    label: "📰 Blog Home",
                    type: "link",
                },
                {
                        href: "/blog/tags",
                        label: "🏷️ Tags",
                        type: "link",
                },
            ],
            label: "📰 Blog",
            link: {
                description: "Development updates, deep dives, and release notes.",
                title: "Blog",
                type: "generated-index",
            },
            type: "category",
        },
    ],
};

export default sidebars;
