matrix:
    - name: Markdown
      aspell:
          lang: en
          dictionary:
          wordlists:
              - .wordlist.txt
          encoding: utf-8
          pipeline:
              - pyspelling.filters.markdown:
                markdown_extensions:
                    - pymdownx.superfences
              - pyspelling.filters.html:
                comments: false
                ignores:
                    - code
                    - pre
          sources:
              - "**/*.md"
          default_encoding: utf-8
          exclude:
              - "node_modules/**"
              - "**/node_modules/**"
              - "**/changelog.md"
              - "**/CHANGELOG.md"
              - "**/copilot-instructions.md"
