# This is a Dependabot configuration file for automating dependency updates.
# The configuration is set to version 2 of the Dependabot schema.
# It defines update settings for three package ecosystems: GitHub Actions, Bundler, and npm.
# Each ecosystem has its own update configuration, including:
# - The directory to scan for dependencies (root directory in this case).
# - The schedule for checking updates (daily).
# - Allowing both direct and indirect updates for all packages.
# - Grouping updates by ecosystem with specific patterns for version updates.

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      time: "04:30"
      timezone: "America/Detroit"
    reviewers: ["Nick2bad4u"]
    assignees: ["Nick2bad4u"]
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "all"
    labels:
      - "github-actions"
    groups:
      github-actions:
        applies-to: version-updates
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /electron-app
    schedule:
      interval: weekly
    reviewers: ["Nick2bad4u"]
    assignees: ["Nick2bad4u"]
    versioning-strategy: increase
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "all"
    labels:
      - "npm"
    groups:
      npm-all:
        applies-to: version-updates
        patterns:
          - "*"
    ignore:
      - dependency-name: "@octokit/auth-token"
        versions: ["<4.0.0"]
      - dependency-name: "@octokit/core"
        versions: ["<5.2.1"]
      - dependency-name: "@octokit/graphql"
        versions: ["<7.1.1"]
      - dependency-name: "@octokit/openapi-types"
        versions: ["<20.0.0"]
      - dependency-name: "@octokit/plugin-retry"
        versions: ["<6.1.0"]
      - dependency-name: "@octokit/types"
        versions: ["<12.6.0"]
      - dependency-name: "@octokit/plugin-paginate-rest"
        versions: ["<9.2.2"]
      - dependency-name: "@octokit/plugin-rest-endpoint-methods"
        versions: ["<10.4.1"]
      - dependency-name: "@octokit/endpoint"
        versions: ["<9.0.6"]
      - dependency-name: "@octokit/request"
        versions: ["<8.4.1"]
      - dependency-name: "@octokit/request-error"
        versions: ["<5.1.1"]
      - dependency-name: "readable-stream"
        versions: ["<3.6.2"]
      - dependency-name: "safe-buffer"
        versions: ["<5.2.1"]
      - dependency-name: "string_decoder"
        versions: ["<1.3.0"]
