
ACTION_ACTIONLINT_CONFIG_FILE: ActionLintConfig.yaml
COPYPASTE_JSCPD_CONFIG_FILE: .jscpd.json
CSS_STYLELINT_CONFIG_FILE: stylelint.config.js
DISABLE_ERRORS: true
DISABLE_LINTERS: []
EXCLUDED_DIRECTORIES: [libs, tests, screenshots, node_modules, icons, docs]
FILEIO_REPORTER: true
GITHUB_COMMENT_REPORTER: true
GITHUB_STATUS_REPORTER: true
HTML_HTMLHINT_CONFIG_FILE: .htmlhintrc
JAVASCRIPT_DEFAULT_STYLE: prettier
JAVASCRIPT_PRETTIER_CONFIG_FILE: .prettierrc
JSON_PRETTIER_CONFIG_FILE: .prettierrc.json
JSON_REPORTER: true
MARKDOWN_MARKDOWNLINT_CONFIG_FILE: .markdownlint.json
MARKDOWN_MARKDOWN_LINK_CHECK_CONFIG_FILE: .markdown-link-check.json
MARKDOWN_MARKDOWN_TABLE_FORMATTER_FILTER_REGEX_EXCLUDE: "^.*(CHANGELOG|README|SECURITY)\\.md$"
MARKDOWN_SUMMARY_REPORTER: true
REPOSITORY_CHECKOV_CONFIG_FILE: .checkov.yml
REPOSITORY_DEVSKIM_CONFIG_FILE: .devskim.json
REPOSITORY_KICS_CONFIG_FILE: kics.yaml
SARIF_REPORTER: true
SHOW_ELAPSED_TIME: true
SPELL_LYCHEE_CONFIG_FILE: lychee.toml
TAP_REPORTER: true
YAML_YAMLLINT_CONFIG_FILE: .yamllint.yaml
