repos:
    - repo: https://github.com/gitleaks/gitleaks
      rev: v8.16.3
      hooks:
          - id: gitleaks
    - repo: local
      hooks:
          - id: root-eslint
            name: root eslint
            entry: node scripts/run-eslint.mjs root
            language: system
            pass_filenames: false
          - id: app-eslint
            name: app eslint
            entry: node scripts/run-eslint.mjs app
            language: system
            pass_filenames: false
          - id: docusaurus-eslint
            name: docusaurus eslint
            entry: node scripts/run-eslint.mjs docusaurus
            language: system
            pass_filenames: false
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: end-of-file-fixer
          - id: trailing-whitespace
    - repo: https://github.com/jumanjihouse/pre-commit-hooks
      rev: 3.0.0
      hooks:
          - id: shellcheck
