import nickTwoBadFourU from "eslint-config-nick2bad4u";
import globals from "globals";
import { fileURLToPath } from "node:url";

import {
    rootAlternativeFitViewPath,
    rootAppIconsPath,
    rootAppStaticPath,
} from "./scripts/lib/workspaces.mjs";

const electronAppBasePath = "electron-app";
// eslint-disable-next-line unicorn/prefer-import-meta-properties -- import.meta.dirname is not available across the declared Node >=22.12.0 range.
const rootDirectory = fileURLToPath(new URL(".", import.meta.url));
const sharedConfig = nickTwoBadFourU.createConfig({
    allowDefaultProjectFilePatterns: [],
    rootDirectory,
    tsconfigPaths: ["./tsconfig.eslint.json", "./tsconfig.docusaurus.json"],
});
const dependPlugin = sharedConfig.find((entry) => entry.plugins?.depend)
    ?.plugins.depend;
const rootToolingIgnorePatterns = new Set([
    "script/**/*.{js,jsx,mjs,cjs,ts,tsx,cts,mts}",
    "scripts/**/*.{js,jsx,mjs,cjs,ts,tsx,cts,mts}",
]);
const rootSharedConfig = sharedConfig.map((entry) => {
    if (!entry.ignores) {
        return entry;
    }

    return {
        ...entry,
        ignores: entry.ignores.filter(
            (ignorePattern) => !rootToolingIgnorePatterns.has(ignorePattern)
        ),
    };
});
const electronAppSharedConfig = rootSharedConfig.map((entry) => {
    const configEntry = { ...entry };
    delete configEntry.plugins;

    return {
        ...configEntry,
        basePath: electronAppBasePath,
    };
});

if (!dependPlugin) {
    throw new Error(
        "eslint-config-nick2bad4u must provide eslint-plugin-depend"
    );
}

/** @type {import("eslint").Linter.Config[]} */
const config = [
    {
        ignores: [
            "playwright-report/**",
            "docs/ACCENT_COLOR_CODE_EXAMPLES.js",
            `${rootAlternativeFitViewPath}/**`,
            `${rootAppIconsPath}/**`,
            `${rootAppStaticPath}/**`,
            "test-results/**",
        ],
    },
    {
        basePath: electronAppBasePath,
        ignores: [
            ".cache/**",
            "coverage/**",
            "dist/**",
            "**/main.js",
            "**/*.css",
            "fitParser.js",
            "**/*.html",
            "html/**",
            "main-ui.js",
            "main/**/*.js",
            "preload.js",
            "preload/**/*.js",
            "renderer/leafletMeasureLite.js",
            "shared/**/*.js",
            "temp-win7/**",
            "test-results/**",
            "types/**",
            "ui/**/*.js",
            "utils/**/*.js",
            "utils.js",
            "windowStateUtils.js",
        ],
    },
    ...rootSharedConfig,
    ...electronAppSharedConfig,
    {
        basePath: electronAppBasePath,
        files: ["**/*.{cjs,js,mjs,ts,tsx}"],
        rules: {
            "@typescript-eslint/array-type": "off",
            "@typescript-eslint/consistent-indexed-object-style": "off",
            "@typescript-eslint/consistent-type-definitions": "off",
            "@typescript-eslint/dot-notation": "off",
            "@typescript-eslint/no-confusing-void-expression": "off",
            "@typescript-eslint/no-base-to-string": "off",
            "@typescript-eslint/no-deprecated": "off",
            "@typescript-eslint/no-dynamic-delete": "off",
            "@typescript-eslint/no-invalid-void-type": "off",
            "@typescript-eslint/no-misused-promises": "off",
            "@typescript-eslint/no-misused-spread": "off",
            "@typescript-eslint/no-redundant-type-constituents": "off",
            "@typescript-eslint/no-require-imports": "off",
            "@typescript-eslint/no-unsafe-argument": "off",
            "@typescript-eslint/no-unsafe-assignment": "off",
            "@typescript-eslint/no-unsafe-call": "off",
            "@typescript-eslint/no-unsafe-member-access": "off",
            "@typescript-eslint/no-unsafe-return": "off",
            "@typescript-eslint/no-unnecessary-type-conversion": "off",
            "@typescript-eslint/no-unnecessary-type-parameters": "off",
            "@typescript-eslint/no-unused-vars": [
                "error",
                {
                    argsIgnorePattern: "^_",
                    caughtErrorsIgnorePattern: "^_",
                    destructuredArrayIgnorePattern: "^_",
                    varsIgnorePattern: "^_",
                },
            ],
            "@typescript-eslint/no-floating-promises": "off",
            "@typescript-eslint/prefer-nullish-coalescing": "off",
            "@typescript-eslint/prefer-optional-chain": "off",
            "@typescript-eslint/require-await": "off",
            "@typescript-eslint/restrict-template-expressions": "off",
            "@typescript-eslint/switch-exhaustiveness-check": "off",
            "@typescript-eslint/unbound-method": "off",
            "@typescript-eslint/use-unknown-in-catch-callback-variable": "off",
            "canonical/filename-no-index": "off",
            "canonical/no-reassign-imports": "off",
            "capitalized-comments": "off",
            complexity: "off",
            "default-case": "off",
            "func-names": "off",
            "import-x/max-dependencies": "off",
            "import-x/no-unassigned-import": "off",
            "listeners/matching-remove-event-listener": "off",
            "listeners/no-inline-function-event-listener": "off",
            "listeners/no-missing-remove-event-listener": "off",
            "max-classes-per-file": "off",
            "max-depth": "off",
            "max-lines-per-function": "off",
            "n/callback-return": "off",
            "n/global-require": "off",
            "n/no-missing-require": "off",
            "n/no-process-env": "off",
            "n/no-sync": "off",
            "n/no-unsupported-features/node-builtins": "off",
            "new-cap": "off",
            "no-await-in-loop": "off",
            "no-barrel-files/no-barrel-files": "off",
            "no-bitwise": "off",
            "no-console": "off",
            "no-empty": "off",
            "no-eq-null": "off",
            "no-multi-assign": "off",
            "no-new": "off",
            "no-plusplus": "off",
            "no-underscore-dangle": "off",
            "no-useless-assignment": "off",
            "perfectionist/sort-classes": "off",
            "perfectionist/sort-imports": "off",
            "perfectionist/sort-interfaces": "off",
            "perfectionist/sort-intersection-types": "off",
            "perfectionist/sort-modules": "off",
            "perfectionist/sort-named-imports": "off",
            "perfectionist/sort-object-types": "off",
            "perfectionist/sort-objects": "off",
            "perfectionist/sort-union-types": "off",
            "perfectionist/sort-variable-declarations": "off",
            "preserve-caught-error": "off",
            "prefer-const": "off",
            "prefer-named-capture-group": "off",
            "promise/always-return": "off",
            "promise/param-names": "off",
            "regexp/no-dupe-disjunctions": "off",
            "regexp/no-super-linear-move": "off",
            "regexp/no-unused-capturing-group": "off",
            "regexp/prefer-named-capture-group": "off",
            "regexp/require-unicode-regexp": "off",
            "regexp/require-unicode-sets-regexp": "off",
            "regexp/sort-character-class-elements": "off",
            "unicorn/consistent-function-scoping": "off",
            "unicorn/filename-case": "off",
            "unicorn/no-array-callback-reference": "off",
            "unicorn/no-array-reduce": "off",
            "unicorn/no-array-sort": "off",
            "unicorn/no-object-as-default-parameter": "off",
            "unicorn/no-unused-properties": "off",
            "unicorn/prefer-json-parse-buffer": "off",
            "unicorn/prefer-blob-reading-methods": "off",
            "unicorn/prefer-dom-node-remove": "off",
            "unicorn/prefer-logical-operator-over-ternary": "off",
            "unicorn/prefer-module": "off",
            "unicorn/prefer-query-selector": "off",
            "unicorn/prefer-spread": "off",
            "unicorn/prefer-structured-clone": "off",
            "vars-on-top": "off",
        },
    },
    {
        basePath: electronAppBasePath,
        files: [
            "fitParser.ts",
            "main.ts",
            "preload.ts",
        ],
        languageOptions: {
            globals: globals.node,
        },
        rules: {
            "@typescript-eslint/consistent-type-imports": "off",
            "@typescript-eslint/explicit-member-accessibility": "off",
            "@typescript-eslint/no-require-imports": "off",
            "@typescript-eslint/no-unnecessary-type-parameters": "off",
            "@typescript-eslint/no-unsafe-type-assertion": "off",
            "@typescript-eslint/prefer-readonly-parameter-types": "off",
            "import-x/no-commonjs": "off",
            "import-x/unambiguous": "off",
            "n/no-missing-require": [
                "error",
                {
                    tryExtensions: [
                        ".js",
                        ".json",
                        ".node",
                        ".ts",
                    ],
                },
            ],
            "n/prefer-global/buffer": "off",
            "no-undef": "off",
            "perfectionist/sort-interfaces": "off",
            "perfectionist/sort-modules": "off",
            "tsdoc/syntax": "off",
            "unicorn/filename-case": "off",
            "unicorn/prefer-module": "off",
        },
    },
    {
        files: ["global.d.ts"],
        rules: {
            "n/no-extraneous-import": "off",
            "n/no-unpublished-import": "off",
        },
    },
    {
        basePath: electronAppBasePath,
        files: ["main-ui.ts", "main.ts"],
        rules: {
            "@typescript-eslint/no-unsafe-type-assertion": "off",
            "@typescript-eslint/prefer-readonly-parameter-types": "off",
        },
    },
    {
        basePath: electronAppBasePath,
        files: ["renderer.ts"],
        rules: {
            "@typescript-eslint/ban-ts-comment": "off",
            "@typescript-eslint/no-redundant-type-constituents": "off",
            "@typescript-eslint/no-unsafe-assignment": "off",
            "@typescript-eslint/no-unsafe-call": "off",
            "@typescript-eslint/no-unsafe-return": "off",
            "@typescript-eslint/no-unsafe-type-assertion": "off",
            "@typescript-eslint/prefer-readonly-parameter-types": "off",
            "runtime-cleanup/no-floating-timers": "off",
            "runtime-cleanup/no-unmanaged-event-listeners": "off",
            "tsdoc/syntax": "off",
            "typedoc/no-duplicate-param-tags": "off",
            "typedoc/no-extra-param-tags": "off",
            "typedoc/no-unknown-tags": "off",
            "typedoc/require-throws-tag": "off",
        },
    },
    {
        basePath: electronAppBasePath,
        files: ["fitParser.ts"],
        rules: {
            "@typescript-eslint/consistent-type-imports": "off",
            "@typescript-eslint/no-unsafe-type-assertion": "off",
            "@typescript-eslint/prefer-readonly-parameter-types": "off",
            "n/global-require": "off",
            "no-unsanitized/method": "off",
        },
    },
    {
        files: ["playwright.config.ts"],
        rules: {
            "module-interop/no-require-esm": "off",
        },
    },
    {
        files: ["vitest.config.ts"],
        rules: {
            "import-x/extensions": "off",
        },
    },
    {
        files: [
            "**/*.spec.js",
            "**/*.spec.ts",
            "**/*.test.js",
            "**/*.test.ts",
            "tests/**",
        ],
        linterOptions: {
            reportUnusedDisableDirectives: "off",
        },
        rules: {
            "@typescript-eslint/await-thenable": "off",
            "@typescript-eslint/ban-ts-comment": "off",
            "@typescript-eslint/class-methods-use-this": "off",
            "@typescript-eslint/consistent-type-definitions": "off",
            "@typescript-eslint/consistent-indexed-object-style": "off",
            "@typescript-eslint/consistent-type-imports": "off",
            "@typescript-eslint/dot-notation": "off",
            "@typescript-eslint/explicit-module-boundary-types": "off",
            "@typescript-eslint/member-ordering": "off",
            "@typescript-eslint/explicit-member-accessibility": "off",
            "@typescript-eslint/no-deprecated": "off",
            "@typescript-eslint/no-dynamic-delete": "off",
            "@typescript-eslint/no-base-to-string": "off",
            "@typescript-eslint/no-explicit-any": "off",
            "@typescript-eslint/no-extraneous-class": "off",
            "@typescript-eslint/no-empty-function": "off",
            "@typescript-eslint/no-confusing-void-expression": "off",
            "@typescript-eslint/no-implied-eval": "off",
            "@typescript-eslint/no-invalid-void-type": "off",
            "@typescript-eslint/no-misused-promises": "off",
            "@typescript-eslint/no-misused-spread": "off",
            "@typescript-eslint/no-non-null-assertion": "off",
            "@typescript-eslint/non-nullable-type-assertion-style": "off",
            "@typescript-eslint/no-redundant-type-constituents": "off",
            "@typescript-eslint/no-unnecessary-type-assertion": "off",
            "@typescript-eslint/no-unnecessary-condition": "off",
            "@typescript-eslint/no-unsafe-argument": "off",
            "@typescript-eslint/no-unsafe-assignment": "off",
            "@typescript-eslint/no-unsafe-call": "off",
            "@typescript-eslint/no-unsafe-member-access": "off",
            "@typescript-eslint/no-unsafe-return": "off",
            "@typescript-eslint/no-unused-expressions": "off",
            "@typescript-eslint/no-useless-default-assignment": "off",
            "@typescript-eslint/no-require-imports": "off",
            "@typescript-eslint/no-unnecessary-type-conversion": "off",
            "@typescript-eslint/no-unnecessary-type-parameters": "off",
            "@typescript-eslint/only-throw-error": "off",
            "@typescript-eslint/parameter-properties": "off",
            "@typescript-eslint/prefer-function-type": "off",
            "@typescript-eslint/prefer-nullish-coalescing": "off",
            "@typescript-eslint/prefer-optional-chain": "off",
            "@typescript-eslint/promise-function-async": "off",
            "@typescript-eslint/prefer-regexp-exec": "off",
            "@typescript-eslint/prefer-promise-reject-errors": "off",
            "@typescript-eslint/require-array-sort-compare": "off",
            "@typescript-eslint/return-await": "off",
            "@typescript-eslint/restrict-plus-operands": "off",
            "@typescript-eslint/require-await": "off",
            "@typescript-eslint/restrict-template-expressions": "off",
            "@typescript-eslint/strict-boolean-expressions": "off",
            "@typescript-eslint/strict-void-return": "off",
            "@typescript-eslint/unbound-method": "off",
            "@typescript-eslint/use-unknown-in-catch-callback-variable": "off",
            "@eslint-community/eslint-comments/require-description": "off",
            "case-police/string-check": "off",
            "capitalized-comments": "off",
            "comment-length/limit-single-line-comments": "off",
            "arrow-body-style": "off",
            complexity: "off",
            "import-x/newline-after-import": "off",
            "import-x/no-commonjs": "off",
            "import-x/extensions": "off",
            "import-x/first": "off",
            "import-x/unambiguous": "off",
            "import-x/no-duplicates": "off",
            "import-x/no-dynamic-require": "off",
            "import-x/no-unassigned-import": "off",
            "import-x/no-unresolved": "off",
            "logical-assignment-operators": "off",
            "listeners/matching-remove-event-listener": "off",
            "listeners/no-inline-function-event-listener": "off",
            "listeners/no-missing-remove-event-listener": "off",
            "max-lines-per-function": "off",
            "module-interop/no-require-esm": "off",
            "n/callback-return": "off",
            "n/global-require": "off",
            "n/no-callback-literal": "off",
            "n/no-missing-require": "off",
            "n/no-process-env": "off",
            "n/no-unsupported-features/node-builtins": "off",
            "n/prefer-global/process": "off",
            "n/prefer-global/buffer": "off",
            "n/prefer-node-protocol": "off",
            "no-bitwise": "off",
            "no-duplicate-imports": "off",
            "no-eq-null": "off",
            "no-empty": "off",
            "no-implicit-coercion": "off",
            "no-multi-assign": "off",
            "no-proto": "off",
            "no-script-url": "off",
            "no-template-curly-in-string": "off",
            "no-useless-catch": "off",
            "no-useless-escape": "off",
            "no-useless-call": "off",
            "no-useless-return": "off",
            "perfectionist/sort-imports": "off",
            "perfectionist/sort-interfaces": "off",
            "perfectionist/sort-intersection-types": "off",
            "perfectionist/sort-array-includes": "off",
            "perfectionist/sort-arrays": "off",
            "perfectionist/sort-classes": "off",
            "perfectionist/sort-maps": "off",
            "perfectionist/sort-modules": "off",
            "perfectionist/sort-named-imports": "off",
            "perfectionist/sort-object-types": "off",
            "perfectionist/sort-objects": "off",
            "perfectionist/sort-sets": "off",
            "perfectionist/sort-switch-case": "off",
            "perfectionist/sort-union-types": "off",
            "perfectionist/sort-variable-declarations": "off",
            "prefer-named-capture-group": "off",
            "prefer-const": "off",
            "prefer-exponentiation-operator": "off",
            "prefer-object-spread": "off",
            "prefer-object-has-own": "off",
            "prefer-template": "off",
            "promise/always-return": "off",
            "promise/no-callback-in-promise": "off",
            "promise/prefer-await-to-then": "off",
            "math/prefer-exponentiation-operator": "off",
            "math/prefer-math-hypot": "off",
            "math/prefer-number-min-safe-integer": "off",
            "regexp/optimal-quantifier-concatenation": "off",
            "regexp/letter-case": "off",
            "regexp/match-any": "off",
            "regexp/no-super-linear-backtracking": "off",
            "regexp/no-super-linear-move": "off",
            "regexp/no-unused-capturing-group": "off",
            "regexp/no-useless-flag": "off",
            "regexp/prefer-character-class": "off",
            "regexp/prefer-named-capture-group": "off",
            "regexp/prefer-quantifier": "off",
            "regexp/prefer-regexp-exec": "off",
            "regexp/prefer-w": "off",
            "regexp/use-ignore-case": "off",
            "regexp/require-unicode-regexp": "off",
            "regexp/require-unicode-sets-regexp": "off",
            "regexp/sort-alternatives": "off",
            "regexp/sort-character-class-elements": "off",
            "require-atomic-updates": "off",
            "security/detect-non-literal-regexp": "off",
            "security/detect-possible-timing-attacks": "off",
            "security/detect-unsafe-regex": "off",
            "sdl/no-inner-html": "off",
            "test-signal/no-duplicate-assertions": "off",
            "test-signal/no-weak-existence-assertions": "off",
            "test-signal/no-weak-truthy-assertions": "off",
            "test-signal/require-negative-path": "off",
            "tsdoc/syntax": "off",
            "typedoc/no-unknown-tags": "off",
            "unicorn/better-regex": "off",
            "unicorn/consistent-existence-index-check": "off",
            "unicorn/catch-error-name": "off",
            "unicorn/escape-case": "off",
            "unicorn/explicit-length-check": "off",
            "unicorn/import-style": "off",
            "unicorn/no-array-reverse": "off",
            "unicorn/no-array-for-each": "off",
            "unicorn/no-array-reduce": "off",
            "unicorn/no-array-sort": "off",
            "unicorn/no-immediate-mutation": "off",
            "unicorn/no-invalid-remove-event-listener": "off",
            "unicorn/no-lonely-if": "off",
            "unicorn/no-new-array": "off",
            "unicorn/no-negated-condition": "off",
            "unicorn/no-unnecessary-array-splice-count": "off",
            "unicorn/no-unreadable-array-destructuring": "off",
            "unicorn/no-typeof-undefined": "off",
            "unicorn/no-zero-fractions": "off",
            "unicorn/numeric-separators-style": "off",
            "unicorn/prefer-add-event-listener": "off",
            "unicorn/prefer-array-find": "off",
            "unicorn/prefer-code-point": "off",
            "unicorn/prefer-dom-node-append": "off",
            "unicorn/prefer-dom-node-dataset": "off",
            "unicorn/prefer-dom-node-remove": "off",
            "unicorn/prefer-event-target": "off",
            "unicorn/prefer-global-this": "off",
            "unicorn/prefer-json-parse-buffer": "off",
            "unicorn/prefer-module": "off",
            "unicorn/prefer-native-coercion-functions": "off",
            "unicorn/prefer-node-protocol": "off",
            "unicorn/prefer-number-properties": "off",
            "unicorn/prefer-optional-catch-binding": "off",
            "unicorn/prefer-query-selector": "off",
            "unicorn/prefer-switch": "off",
            "unicorn/prefer-ternary": "off",
            "unicorn/relative-url-style": "off",
            "unicorn/prefer-string-raw": "off",
            "unicorn/prefer-string-replace-all": "off",
            "unicorn/prefer-top-level-await": "off",
            "unicorn/prefer-type-error": "off",
            "unicorn/switch-case-braces": "off",
            "unicorn/text-encoding-identifier-case": "off",
            "vars-on-top": "off",
            "vitest/consistent-test-filename": "off",
            "vitest/consistent-test-it": "off",
            "vitest/hoisted-apis-on-top": "off",
            "vitest/max-expects": "off",
            "vitest/no-alias-methods": "off",
            "vitest/no-conditional-in-test": "off",
            "vitest/no-duplicate-hooks": "off",
            "vitest/no-hooks": "off",
            "vitest/no-identical-title": "off",
            "vitest/no-standalone-expect": "off",
            "vitest/padding-around-after-each-blocks": "off",
            "vitest/padding-around-all": "off",
            "vitest/padding-around-before-each-blocks": "off",
            "vitest/padding-around-describe-blocks": "off",
            "vitest/padding-around-expect-groups": "off",
            "vitest/padding-around-test-blocks": "off",
            "vitest/prefer-called-exactly-once-with": "off",
            "vitest/prefer-called-once": "off",
            "vitest/prefer-called-with": "off",
            "vitest/prefer-comparison-matcher": "off",
            "vitest/prefer-describe-function-title": "off",
            "vitest/prefer-equality-matcher": "off",
            "vitest/prefer-expect-assertions": "off",
            "vitest/prefer-expect-resolves": "off",
            "vitest/prefer-expect-type-of": "off",
            "vitest/prefer-hooks-in-order": "off",
            "vitest/prefer-import-in-mock": "off",
            "vitest/prefer-importing-vitest-globals": "off",
            "vitest/prefer-lowercase-title": "off",
            "vitest/prefer-mock-promise-shorthand": "off",
            "vitest/prefer-mock-return-shorthand": "off",
            "vitest/prefer-spy-on": "off",
            "vitest/prefer-strict-equal": "off",
            "vitest/prefer-strict-boolean-matchers": "off",
            "vitest/prefer-to-be": "off",
            "vitest/prefer-to-be-falsy": "off",
            "vitest/prefer-to-be-truthy": "off",
            "vitest/prefer-called-times": "off",
            "vitest/prefer-to-contain": "off",
            "vitest/prefer-to-have-been-called-times": "off",
            "vitest/prefer-to-have-length": "off",
            "vitest/prefer-vi-mocked": "off",
            "vitest/require-hook": "off",
            "vitest/require-mock-type-parameters": "off",
            "vitest/require-top-level-describe": "off",
            "vitest/unbound-method": "off",
        },
    },
    {
        files: ["scripts/**/*.{cjs,js,mjs,ts}"],
        languageOptions: {
            globals: globals.node,
        },
        rules: {
            "@typescript-eslint/await-thenable": "off",
            "@typescript-eslint/dot-notation": "off",
            "@typescript-eslint/no-unnecessary-condition": "off",
            "@typescript-eslint/no-unsafe-argument": "off",
            "@typescript-eslint/no-unsafe-assignment": "off",
            "@typescript-eslint/no-unsafe-call": "off",
            "@typescript-eslint/no-unsafe-member-access": "off",
            "@typescript-eslint/no-unsafe-return": "off",
            "@typescript-eslint/prefer-for-of": "off",
            "@typescript-eslint/prefer-optional-chain": "off",
            "@typescript-eslint/prefer-nullish-coalescing": "off",
            "@typescript-eslint/prefer-regexp-exec": "off",
            "@typescript-eslint/require-array-sort-compare": "off",
            "@typescript-eslint/restrict-plus-operands": "off",
            "@typescript-eslint/restrict-template-expressions": "off",
            "@typescript-eslint/strict-boolean-expressions": "off",
            "@typescript-eslint/use-unknown-in-catch-callback-variable": "off",
            "case-police/string-check": "off",
            "capitalized-comments": "off",
            "canonical/no-re-export": "off",
            complexity: "off",
            "max-depth": "off",
            "max-lines-per-function": "off",
            "import-x/newline-after-import": "off",
            "import-x/no-commonjs": "off",
            "n/hashbang": "off",
            "n/no-process-env": "off",
            "n/no-sync": "off",
            "n/no-unsupported-features/node-builtins": "off",
            "n/prefer-global/process": "off",
            "no-console": "off",
            "no-await-in-loop": "off",
            "no-template-curly-in-string": "off",
            "perfectionist/sort-imports": "off",
            "perfectionist/sort-array-includes": "off",
            "perfectionist/sort-maps": "off",
            "perfectionist/sort-modules": "off",
            "perfectionist/sort-named-imports": "off",
            "perfectionist/sort-objects": "off",
            "perfectionist/sort-sets": "off",
            "prefer-named-capture-group": "off",
            "promise/prefer-await-to-then": "off",
            "regexp/prefer-named-capture-group": "off",
            "regexp/prefer-regexp-exec": "off",
            "regexp/prefer-lookaround": "off",
            "regexp/no-super-linear-backtracking": "off",
            "regexp/require-unicode-regexp": "off",
            "regexp/require-unicode-sets-regexp": "off",
            "regexp/sort-character-class-elements": "off",
            "security/detect-non-literal-fs-filename": "off",
            "unicorn/better-regex": "off",
            "unicorn/import-style": "off",
            "unicorn/no-array-callback-reference": "off",
            "unicorn/no-array-sort": "off",
            "unicorn/no-for-loop": "off",
            "unicorn/no-object-as-default-parameter": "off",
            "unicorn/prefer-json-parse-buffer": "off",
            "unicorn/prefer-string-replace-all": "off",
            "unicorn/prefer-switch": "off",
            "unicorn/prefer-top-level-await": "off",
        },
    },
    {
        files: ["eslint.config.mjs"],
        rules: {
            "perfectionist/sort-objects": "off",
        },
    },
    {
        files: [".github/workflows/Build.yml"],
        rules: {
            "github-actions/max-jobs-per-action": ["error", 4],
        },
    },
    {
        files: [".github/workflows/*-caller.yml"],
        rules: {
            "github-actions/no-external-job": "off",
            "github-actions/pin-action-shas": "off",
            "github-actions/require-dependency-review-action": "off",
        },
    },
    {
        files: [".github/agents/beastmode.agent.md"],
        rules: {
            "copilot/prefer-qualified-tools": "off",
        },
    },
    {
        files: ["package.json"],
        rules: {
            "depend/ban-dependencies": [
                "error",
                {
                    allowed: ["jquery"],
                },
            ],
            "package-json/require-dependencies": "off",
            "package-json/require-peerDependencies": "off",
        },
    },
    {
        files: ["tests/unit/**/*.{spec,test}.{js,ts}"],
        linterOptions: {
            reportUnusedDisableDirectives: "off",
        },
        rules: {
            "vitest/no-hooks": "off",
            "vitest/padding-around-after-each-blocks": "off",
            "vitest/padding-around-all": "off",
            "vitest/padding-around-before-each-blocks": "off",
            "vitest/padding-around-describe-blocks": "off",
            "vitest/padding-around-expect-groups": "off",
            "vitest/padding-around-test-blocks": "off",
            "vitest/prefer-strict-equal": "off",
            "vitest/prefer-to-be": "off",
            "vitest/prefer-to-be-falsy": "off",
            "vitest/prefer-to-be-truthy": "off",
            "vitest/require-top-level-describe": "off",
        },
    },
    {
        files: ["tests/playwright/**/*.{mts,ts}"],
        languageOptions: {
            globals: globals.node,
        },
        rules: {
            "@typescript-eslint/strict-void-return": "off",
            "testing-library/prefer-screen-queries": "off",
            "vitest/consistent-test-filename": "off",
            "vitest/padding-around-all": "off",
            "vitest/padding-around-expect-groups": "off",
            "vitest/prefer-importing-vitest-globals": "off",
            "vitest/unbound-method": "off",
        },
    },
    {
        files: ["tests/vitest/stubs/**/*.cjs"],
        languageOptions: {
            globals: globals.node,
        },
        rules: {
            "@typescript-eslint/no-require-imports": "off",
            "import-x/no-commonjs": "off",
            "import-x/unambiguous": "off",
            "n/no-missing-require": "off",
            "unicorn/prefer-module": "off",
        },
    },
    {
        files: ["tests/vitest/setupVitest.mjs"],
        languageOptions: {
            globals: globals.node,
        },
        linterOptions: {
            reportUnusedDisableDirectives: "off",
        },
        rules: {
            "@typescript-eslint/strict-void-return": "off",
            "vitest/no-duplicate-hooks": "off",
            "vitest/no-hooks": "off",
            "vitest/prefer-hooks-in-order": "off",
            "vitest/prefer-import-in-mock": "off",
            "vitest/prefer-mock-return-shorthand": "off",
            "vitest/prefer-spy-on": "off",
            "vitest/require-mock-type-parameters": "off",
            "vitest/require-top-level-describe": "off",
            "vitest/unbound-method": "off",
        },
    },
    {
        files: ["electron-builder.config.cjs"],
        languageOptions: {
            globals: globals.node,
        },
        rules: {
            "@typescript-eslint/no-require-imports": "off",
            "import-x/extensions": "off",
            "import-x/no-commonjs": "off",
            "import-x/unambiguous": "off",
            "no-template-curly-in-string": "off",
            "perfectionist/sort-objects": "off",
            "unicorn/prefer-module": "off",
        },
    },
];

export default config;
