// Enhanced chart fields with better categorization - match actual FIT file field names
export const chartFields = [
    "speed",
    "heartRate",
    "altitude",
    "power",
    "cadence",
    "temperature",
    "distance",
    "enhancedSpeed",
    "enhancedAltitude",
    "resistance",
    "flow",
    "grit",
    "positionLat",
    "positionLong",
];
export const fieldLabels = {
    speed: "Speed",
    heartRate: "Heart Rate",
    altitude: "Altitude",
    power: "Power",
    cadence: "Cadence",
    temperature: "Temperature",
    distance: "Distance",
    enhancedSpeed: "Enhanced Speed",
    enhancedAltitude: "Enhanced Altitude",
    resistance: "Resistance",
    flow: "Flow",
    grit: "Grit",
    positionLat: "Latitude",
    positionLong: "Longitude",
    gps_track: "GPS Track",
    speed_vs_distance: "Speed vs Distance",
    power_vs_hr: "Power vs Heart Rate",
    altitude_profile: "Altitude Profile",
    hr_zone_doughnut: "HR Zone Distribution",
    hr_zone_bar: "HR Zone Time",
    power_zone_doughnut: "Power Zone Distribution",
    power_zone_bar: "Power Zone Time",
};
// Enhanced color scheme with better accessibility - match actual field names
export const fieldColors = {
    speed: "#1976d2",
    heartRate: "#e53935",
    altitude: "#43a047",
    power: "#ff9800",
    cadence: "#8e24aa",
    temperature: "#00bcd4",
    distance: "#607d8b",
    enhancedSpeed: "#009688",
    enhancedAltitude: "#cddc39",
    resistance: "#795548",
    flow: "#c42196",
    grit: "#6e1cbb",
    positionLat: "#ff5722",
    positionLong: "#3f51b5",
    gps_track: "#4caf50",
    speed_vs_distance: "#2196f3",
    power_vs_hr: "#ff5722",
    altitude_profile: "#8bc34a",
    hr_zone_doughnut: "#e53935",
    hr_zone_bar: "#d32f2f",
    power_zone_doughnut: "#ff9800",
    power_zone_bar: "#f57c00",
};
