// Enhanced configuration for chart customization
const defaultMaxPoints = 250;
const maxPointsOptions = [1, 10, 25, 50, 100, 200, 250, 500, 700, 1000, 2000, 3000, 5000, 10000, 50000, 100000, 1000000, 'all'];
// Comprehensive chart configuration options
export const chartOptionsConfig = [
	{
		id: 'maxpoints',
		label: 'Max Points',
		type: 'select',
		options: maxPointsOptions,
		default: defaultMaxPoints,
		description: 'Maximum number of data points to display',
	},
	{
		id: 'chartType',
		label: 'Chart Type',
		type: 'select',
		options: ['line', 'bar', 'scatter', 'area'],
		default: 'line',
		description: 'Type of chart visualization',
	},
	{
		id: 'interpolation',
		label: 'Interpolation',
		type: 'select',
		options: ['linear', 'monotone', 'stepped'],
		default: 'monotone',
		description: 'Line interpolation method',
	},
	{
		id: 'animation',
		label: 'Animation',
		type: 'select',
		options: ['smooth', 'fast', 'none'],
		default: 'smooth',
		description: 'Chart animation style',
	},
	{
		id: 'exportTheme',
		label: 'Export Theme',
		type: 'select',
		options: ['light', 'dark', 'transparent'],
		default: 'light',
		description: 'Background theme for exported images',
	},
	{
		id: 'showGrid',
		label: 'Grid',
		type: 'toggle',
		options: ['on', 'off'],
		default: 'on',
		description: 'Show/hide chart grid lines',
	},
	{
		id: 'showLegend',
		label: 'Legend',
		type: 'toggle',
		options: ['on', 'off'],
		default: 'on',
		description: 'Show/hide chart legend',
	},
	{
		id: 'showTitle',
		label: 'Title',
		type: 'toggle',
		options: ['on', 'off'],
		default: 'on',
		description: 'Show/hide chart titles',
	},
	{
		id: 'showPoints',
		label: 'Data Points',
		type: 'toggle',
		options: ['on', 'off'],
		default: 'off',
		description: 'Show/hide individual data points',
	},
	{
		id: 'showFill',
		label: 'Fill Area',
		type: 'toggle',
		options: ['on', 'off'],
		default: 'on',
		description: 'Fill area under the line',
	}, {
		id: 'smoothing',
		label: 'Line Smoothing',
		type: 'range',
		min: 0,
		max: 1,
		step: 0.1,
		default: 0.4,
		description: 'Line curve smoothing amount',
	},
	{
		id: 'timeUnits',
		label: 'Time Units',
		type: 'select',
		options: ['seconds', 'minutes', 'hours'],
		default: 'seconds',
		description: 'Units for time display on axes and tooltips',
	},
	{
		id: 'distanceUnits',
		label: 'Distance Units',
		type: 'select',
		options: ['meters', 'kilometers', 'feet', 'miles'],
		default: 'kilometers',
		description: 'Units for distance/altitude display on axes and tooltips',
	},
	{
		id: 'temperatureUnits',
		label: 'Temperature Units',
		type: 'select',
		options: ['celsius', 'fahrenheit'],
		default: 'celsius',
		description: 'Units for temperature display on axes and tooltips',
	},
];
