name: Build and Release Electron App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  bump-version:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: electron-app
    outputs:
      new_version: ${{ steps.bump.outputs.new_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug Step - Show git diff for electron-app
        run: |
          echo "--- GIT DIFF OUTPUT (since last tag) ---"
          LAST_REF=$(git describe --tags --match "v*" --abbrev=0 2>/dev/null || git rev-list --max-parents=0 HEAD)
          git diff --name-status "$LAST_REF" -- electron-app/
          echo "--- END GIT DIFF OUTPUT ---"

      - name: Bump version
        id: bump
        run: |
          if [ ! -f package.json ]; then
            echo "Error: package.json not found" >&2
            exit 1
          fi
          if ! jq empty package.json >/dev/null 2>&1; then
            echo "Error: package.json is not valid JSON" >&2
            exit 1
          fi
          # Find last tag (always with v prefix) or initial commit
          LAST_REF=$(git describe --tags --match "v*" --abbrev=0 2>/dev/null || git rev-list --max-parents=0 HEAD)
          # Check for changes in electron-app dir since last ref
          if git diff --quiet "$LAST_REF" -- electron-app/; then
            BUMP_TYPE=patch
          else
            BUMP_TYPE=minor_or_major
          fi
          VERSION=$(jq -r .version package.json)
          MAJOR=$(echo $VERSION | cut -d. -f1)
          MINOR=$(echo $VERSION | cut -d. -f2)
          PATCH=$(echo $VERSION | cut -d. -f3)
          if [ "$BUMP_TYPE" = "patch" ]; then
            NEW_VERSION="$MAJOR.$MINOR.$(($PATCH + 1))"
          else
            if [ "$MINOR" -lt 9 ]; then
              NEW_VERSION="$MAJOR.$(($MINOR + 1)).0"
            else
              NEW_VERSION="$(($MAJOR + 1)).0.0"
            fi
          fi
          jq --arg v "$NEW_VERSION" '.version = $v' package.json > tmp.json && mv tmp.json package.json
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Tag new version
        if: steps.bump.outputs.new_version != ''
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag -a "v${{ steps.bump.outputs.new_version }}" -m "Release v${{ steps.bump.outputs.new_version }}"
          git push origin "v${{ steps.bump.outputs.new_version }}"
        working-directory: electron-app

      - name: Commit and push version bump
        uses: EndBug/add-and-commit@v9
        with:
          message: "Bump version to ${{ steps.bump.outputs.new_version }}"
          add: "package.json"
          cwd: electron-app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload bumped package.json
        uses: actions/upload-artifact@v4
        with:
          name: bumped-package-json
          path: electron-app/package.json

  build:
    needs: bump-version
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [x64, ia32]
        exclude:
          # Exclude macOS with ia32 architecture as it is not supported by Electron
          - os: macos-latest
            arch: ia32
          # Exclude Ubuntu with ia32 architecture as it is not commonly used and not officially supported
          - os: ubuntu-latest
            arch: ia32
    defaults:
      run:
        working-directory: electron-app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download bumped package.json
        uses: actions/download-artifact@v4
        with:
          name: bumped-package-json
          path: ./electron-app

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: |
            ${{ runner.os == 'Windows' && 'C:\\Users\\runneradmin\\AppData\\Local\\npm-cache' || '~/.npm' }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      # - name: Install electron-builder
      #   run: npm install -D electron-builder

      - name: Build Electron app
        run: |
          npx electron-builder --${{ matrix.os == 'windows-latest' && 'win' || matrix.os == 'macos-latest' && 'mac' || 'linux' }} --${{ matrix.arch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload distributable files as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os }}-${{ matrix.arch }}
          path: |
            electron-app/dist/**/*.exe
            electron-app/dist/**/*.dmg
            electron-app/dist/**/*.AppImage
            electron-app/dist/**/*.snap
            electron-app/dist/**/*.zip

  release:
    needs: [build, bump-version]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Get previous tag
        id: get_prev_tag
        run: |
          git fetch --tags
          TAG_COUNT=$(git tag --sort=-creatordate | wc -l)
          if [ "$TAG_COUNT" -ge 2 ]; then
            PREV_TAG=$(git tag --sort=-creatordate | tail -2 | head -1)
          else
            PREV_TAG=""
          fi
          echo "prev_tag=$PREV_TAG" >> $GITHUB_OUTPUT

      - name: Generate release notes
        id: release_notes
        run: |
          PREV_TAG="${{ steps.get_prev_tag.outputs.prev_tag }}"
          if [ -n "$PREV_TAG" ]; then
            NOTES=$(git log "$PREV_TAG"..HEAD --pretty=format:'- %s%n  - Author: %an <%ae>%n  - Commit: [`%h`](https://github.com/${{ github.repository }}/commit/%H)%n  - Date: %ad%n' --date=short)
          else
            NOTES=$(git log --pretty=format:'- %s%n  - Author: %an <%ae>%n  - Commit: [`%h`](https://github.com/${{ github.repository }}/commit/%H)%n  - Date: %ad%n' --date=short)
          fi
          echo "notes<<EOF" >> $GITHUB_OUTPUT
          echo -e "$NOTES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: List artifacts
        run: ls -R ./artifacts

      - name: Deduplicate and validate distributable files
        run: |
          mkdir -p release-dist
          find ./artifacts -type f \( -name "*.exe" -o -name "*.dmg" -o -name "*.AppImage" -o -name "*.snap" -o -name "*.zip" \) -exec sh -c '
            for filepath; do
              filename=$(basename "$filepath")
              if [ ! -e "release-dist/$filename" ]; then
                # Validate file (e.g., check size or content if needed)
                if [ -s "$filepath" ]; then
                  cp "$filepath" "release-dist/$filename"
                else
                  echo "Skipping invalid or empty file: $filepath"
                fi
              fi
            done
          ' sh {} +

      # This step uses the softprops/action-gh-release action to create or update a GitHub release.
      # It uploads the distributable files generated during the build process and associates them with the release.
      # The release is tagged with the new version and includes release notes generated from the commit history.
      - name: Create or update release with distributable builds
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ needs.bump-version.outputs.new_version }}
          name: FitFileViewer v${{ needs.bump-version.outputs.new_version }}
          body: ${{ steps.release_notes.outputs.notes }}
          files: release-dist/*
          draft: false
          prerelease: false
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
