name: Build and Release Electron App

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: electron-app
    outputs:
      new_version: ${{ steps.bump.outputs.new_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Bump version
        id: bump
        run: |
          VERSION=$(jq -r .version package.json)
          MAJOR=$(echo $VERSION | cut -d. -f1)
          MINOR=$(echo $VERSION | cut -d. -f2)
          PATCH=$(echo $VERSION | cut -d. -f3)
          # Only bump minor, cycling from .1 to .9 then next major
          if [ "$MINOR" -lt 9 ]; then
            NEW_MINOR=$(($MINOR + 1))
            NEW_VERSION="$MAJOR.$NEW_MINOR.$PATCH"
          else
            NEW_MAJOR=$(($MAJOR + 1))
            NEW_VERSION="$NEW_MAJOR.0.$PATCH"
          fi
          jq --arg v "$NEW_VERSION" '.version = $v' package.json > tmp.json && mv tmp.json package.json
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Commit and push version bump
        uses: EndBug/add-and-commit@v9
        with:
          message: "Bump version to ${{ steps.bump.outputs.new_version }}"
          add: "package.json"
          cwd: electron-app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    needs: bump-version
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [x64, ia32]
        exclude:
          - os: macos-latest
            arch: ia32
          - os: ubuntu-latest
            arch: ia32
    defaults:
      run:
        working-directory: electron-app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install electron-builder
        run: npm install -D electron-builder

      - name: Build Electron app
        run: |
          npx electron-builder --${{ matrix.os == 'windows-latest' && 'win' || matrix.os == 'macos-latest' && 'mac' || 'linux' }} --${{ matrix.arch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload dist folder as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os }}-${{ matrix.arch }}
          path: electron-app/dist/

  release:
    needs: [build, bump-version]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Get previous tag
        id: get_prev_tag
        run: |
          git fetch --tags
          PREV_TAG=$(git tag --sort=-creatordate | tail -2 | head -1)
          echo "prev_tag=$PREV_TAG" >> $GITHUB_OUTPUT

      - name: Generate release notes
        id: release_notes
        run: |
          if [ -n "${{ steps.get_prev_tag.outputs.prev_tag }}" ]; then
            NOTES=$(git log ${{ steps.get_prev_tag.outputs.prev_tag }}..HEAD --pretty=format:'* %s (%an)')
          else
            NOTES=$(git log --pretty=format:'* %s (%an)')
          fi
          echo "notes<<EOF" >> $GITHUB_OUTPUT
          echo "$NOTES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create or update release with unzipped builds
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ needs.bump-version.outputs.new_version }}
          name: Release v${{ needs.bump-version.outputs.new_version }}
          body: ${{ steps.release_notes.outputs.notes }}
          files: ./artifacts/**/*.*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
