name: PSSecretScanner

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  pssecret-scanner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # PowerShell is available by default on ubuntu-latest, so no setup step is required
      - name: Install PSSecretScanner
        shell: pwsh
        run: |
          Install-Module -Name PSSecretScanner -Force -Scope CurrentUser
      - name: Run PSSecretScanner
        shell: pwsh
        run: |
          $exclude = if (Test-Path .ignoresecrets) { '-Excludelist .ignoresecrets' } else { '' }
          Import-Module PSSecretScanner
          $results = Find-Secret -Path . $exclude
          $results | Format-Table | Out-String | Write-Host
          if ($results) { Write-Error 'Secrets found!'; exit 1 } else { Write-Host 'No secrets found.' }
