name: Metrics Repository Stats

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Runs daily

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate repository metrics
        uses: lowlighter/metrics@latest
        with:
          template: repository
          filename: metrics.repository.svg
          token: ${{ secrets.GITHUB_TOKEN}}
          user: lowlighter
          repo: metrics
          plugin_lines: yes
          plugin_followup: yes
          plugin_projects: yes
          plugin_projects_repositories: lowlighter/metrics/projects/1
