name: Metrics Repository Stats

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight (UTC)

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate repository metrics
        uses: lowlighter/metrics@latest
        with:
          template: repository
          filename: metrics.repository.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          user: nick2bad4u
          repo: FitFileViewer
          plugin_lines: yes
          plugin_followup: yes
