name: Upload Linux Distributables to Archive.org

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build and Release Electron App"]
    types:
      - completed

concurrency:
  group: IALINUX-${{ github.ref }}
  cancel-in-progress: true

jobs:
  upload-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - name: Download Linux release assets (linux-)
        id: download_linux
        uses: robinraju/release-downloader@daf26c55d821e836577a15f77d86ddc078948b05 # v1.12
        with:
          latest: true
          fileName: "Fit-File-Viewer-linux-*"
          out-file-path: release-dist
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Linux release assets (appimage-)
        id: download_appimage
        uses: robinraju/release-downloader@daf26c55d821e836577a15f77d86ddc078948b05 # v1.12
        with:
          latest: true
          fileName: "Fit-File-Viewer-appimage-*"
          out-file-path: release-dist
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Linux release assets (deb-)
        id: download_deb
        uses: robinraju/release-downloader@daf26c55d821e836577a15f77d86ddc078948b05 # v1.12
        with:
          latest: true
          fileName: "Fit-File-Viewer-deb-*"
          out-file-path: release-dist
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Linux release assets (pacman-)
        id: download_pacman
        uses: robinraju/release-downloader@daf26c55d821e836577a15f77d86ddc078948b05 # v1.12
        with:
          latest: true
          fileName: "Fit-File-Viewer-pacman-*"
          out-file-path: release-dist
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Linux release assets (rpm-)
        id: download_rpm
        uses: robinraju/release-downloader@daf26c55d821e836577a15f77d86ddc078948b05 # v1.12
        with:
          latest: true
          fileName: "Fit-File-Viewer-rpm-*"
          out-file-path: release-dist
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Linux release assets (snap-)
        id: download_snap
        uses: robinraju/release-downloader@daf26c55d821e836577a15f77d86ddc078948b05 # v1.12
        with:
          latest: true
          fileName: "Fit-File-Viewer-snap-*"
          out-file-path: release-dist
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Linux release assets (freebsd-)
        id: download_freebsd
        uses: robinraju/release-downloader@daf26c55d821e836577a15f77d86ddc078948b05 # v1.12
        with:
          latest: true
          fileName: "Fit-File-Viewer-freebsd-*"
          out-file-path: release-dist
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Linux release assets (apk-)
        id: download_apk
        uses: robinraju/release-downloader@daf26c55d821e836577a15f77d86ddc078948b05 # v1.12
        with:
          latest: true
          fileName: "Fit-File-Viewer-apk-*"
          out-file-path: release-dist
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Linux release assets (latest-linux.yml)
        id: download_latest
        uses: robinraju/release-downloader@daf26c55d821e836577a15f77d86ddc078948b05 # v1.12
        with:
          latest: true
          fileName: "latest-linux.yml"
          out-file-path: release-dist
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Linux distributables to archive.org
        uses: Nick2bad4u/internet-archive-upload@latest # v1
        with:
          access-key: ${{ secrets.IA_ACCESS_KEY }}
          secret-key: ${{ secrets.IA_SECRET_KEY }}
          identifier: fitfileviewer-linux-${{ steps.download_linux.outputs.tag_name }}
          files: release-dist/
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
