name: Upload Linux Distributables to Archive.org

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build and Release Electron App"]
    types:
      - completed

concurrency:
  group: IALINUX-${{ github.ref }}
  cancel-in-progress: true

jobs:
  upload-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Download Linux release assets (linux-)
        id: download_linux
        uses: robinraju/release-downloader@v1.12
        with:
          latest: true
          fileName: "Fit-File-Viewer-linux-*"
          out-file-path: release-dist
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Linux release assets (pacman-)
        id: download_pacman
        uses: robinraju/release-downloader@v1.12
        with:
          latest: true
          fileName: "Fit-File-Viewer-pacman-*"
          out-file-path: release-dist
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Linux release assets (rpm-)
        id: download_rpm
        uses: robinraju/release-downloader@v1.12
        with:
          latest: true
          fileName: "Fit-File-Viewer-rpm-*"
          out-file-path: release-dist
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Linux release assets (snap-)
        id: download_snap
        uses: robinraju/release-downloader@v1.12
        with:
          latest: true
          fileName: "Fit-File-Viewer-snap-*"
          out-file-path: release-dist
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Linux release assets (latest-linux.yml)
        id: download_latest
        uses: robinraju/release-downloader@v1.12
        with:
          latest: true
          fileName: "latest-linux.yml"
          out-file-path: release-dist
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Linux distributables to archive.org
        uses: palewire/internet-archive-upload@v1
        with:
          access-key: ${{ secrets.IA_ACCESS_KEY }}
          secret-key: ${{ secrets.IA_SECRET_KEY }}
          identifier: fitfileviewer-linux-${{ steps.download_linux.outputs.tag_name }}
          files: release-dist/
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
