name: Upload Windows Distributables to Archive.org

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build and Release Electron App"]
    types:
      - completed

concurrency:
  group: IAWINDOWS-${{ github.ref }}
  cancel-in-progress: true

jobs:
  upload-windows:
    runs-on: ubuntu-latest
    steps:
      - name: Download Windows release assets (win32-)
        id: download_win32
        uses: robinraju/release-downloader@v1.12
        with:
          latest: true
          fileName: "Fit-File-Viewer-win32-*"
          out-file-path: release-dist
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Windows release assets (windows-)
        id: download_windows
        uses: robinraju/release-downloader@v1.12
        with:
          latest: true
          fileName: "Fit-File-Viewer-windows-*"
          out-file-path: release-dist
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Windows release assets (latest-windows.yml)
        id: download_latest
        uses: robinraju/release-downloader@v1.12
        with:
          latest: true
          fileName: "latest-windows.yml"
          out-file-path: release-dist
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Windows distributables to archive.org
        uses: palewire/internet-archive-upload@v1
        with:
          access-key: ${{ secrets.IA_ACCESS_KEY }}
          secret-key: ${{ secrets.IA_SECRET_KEY }}
          identifier: fitfileviewer-windows-${{ steps.download_windows.outputs.tag_name }}
          files: release-dist/
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
