name: Upload Windows Distributables to Archive.org

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build and Release Electron App"]
    types:
      - completed

concurrency:
  group: IAWINDOWS-${{ github.ref }}
  cancel-in-progress: true

jobs:
  upload-windows:
    runs-on: ubuntu-latest
    steps:
      - name: Download Windows release assets (msi-)
        id: download_msi
        uses: robinraju/release-downloader@v1.12
        with:
          latest: true
          fileName: "Fit-File-Viewer-msi-*"
          out-file-path: release-dist
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Windows release assets (nsis-)
        id: download_nsis
        uses: robinraju/release-downloader@v1.12
        with:
          latest: true
          fileName: "Fit-File-Viewer-nsis-*"
          out-file-path: release-dist
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Windows release assets (portable-)
        id: download_portable
        uses: robinraju/release-downloader@v1.12
        with:
          latest: true
          fileName: "Fit-File-Viewer-portable-*"
          out-file-path: release-dist
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Windows release assets (latest.yml)
        id: download_latest
        uses: robinraju/release-downloader@v1.12
        with:
          latest: true
          fileName: "latest.yml"
          out-file-path: release-dist
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Windows distributables to archive.org
        uses: palewire/internet-archive-upload@v1
        with:
          access-key: ${{ secrets.IA_ACCESS_KEY }}
          secret-key: ${{ secrets.IA_SECRET_KEY }}
          identifier: fitfileviewer-windows-${{ steps.download_msi.outputs.tag_name }}
          files: release-dist/
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
