name: Upload Windows Distributables to Archive.org

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build and Release Electron App"]
    types:
      - completed

concurrency:
  group: IAWINDOWS-${{ github.ref }}
  cancel-in-progress: true

jobs:
  upload-windows:
    runs-on: ubuntu-latest
    steps:
      - name: Download all release assets
        id: download_windows
        uses: robinraju/release-downloader@v1.12
        with:
          latest: true
          fileName: "*"
          out-file-path: release-dist
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: List all Windows distributables
        id: list_files
        run: |
          files=()
          for pattern in \
            "release-dist/Fit-File-Viewer-win32-*.exe" \
            "release-dist/Fit-File-Viewer-win32-*.msi" \
            "release-dist/Fit-File-Viewer-windows-*.exe" \
            "release-dist/Fit-File-Viewer-windows-*.msi" \
            "release-dist/Fit-File-Viewer-windows-*.zip" \
            "release-dist/latest-windows.yml"
          do
            for f in $pattern; do
              [ -e "$f" ] && files+=("$f")
            done
          done
          printf '%s\n' "${files[@]}" > windows-ia-files.txt

      - name: Upload each distributable to archive.org
        run: |
          set -e
          while IFS= read -r file; do
            echo "Uploading $file to archive.org..."
            gh workflow run palewire/internet-archive-upload@v1 \
              --with access-key=${{ secrets.IA_ACCESS_KEY }} \
              --with secret-key=${{ secrets.IA_SECRET_KEY }} \
              --with identifier=fitfileviewer-windows-${{ steps.download_windows.outputs.tag_name }} \
              --with files="$file" || true
          done < windows-ia-files.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
