name: Upload Linux Distributables to Archive.org

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build and Release Electron App"]
    types:
      - completed

concurrency:
  group: IALINUX-${{ github.ref }}
  cancel-in-progress: true

jobs:
  upload-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Download all release assets
        id: download_linux
        uses: robinraju/release-downloader@v1.12
        with:
          latest: true
          fileName: "*"
          out-file-path: release-dist
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: List all Linux distributables
        id: list_files
        run: |
          files=()
          for pattern in \
            "release-dist/Fit-File-Viewer-linux-*.tar.bz2" \
            "release-dist/Fit-File-Viewer-linux-*.tar.gz" \
            "release-dist/Fit-File-Viewer-linux-*.tar.xz" \
            "release-dist/Fit-File-Viewer-linux-*.zip" \
            "release-dist/Fit-File-Viewer-pacman-*.pacman" \
            "release-dist/Fit-File-Viewer-rpm-*.rpm" \
            "release-dist/Fit-File-Viewer-snap-*.snap" \
            "release-dist/latest-linux.yml"
          do
            for f in $pattern; do
              [ -e "$f" ] && files+=("$f")
            done
          done
          printf '%s\n' "${files[@]}" > linux-ia-files.txt

      - name: Upload each distributable to archive.org
        run: |
          set -e
          while IFS= read -r file; do
            echo "Uploading $file to archive.org..."
            gh workflow run palewire/internet-archive-upload@v1 \
              --with access-key=${{ secrets.IA_ACCESS_KEY }} \
              --with secret-key=${{ secrets.IA_SECRET_KEY }} \
              --with identifier=fitfileviewer-linux-${{ steps.download_linux.outputs.tag_name }} \
              --with files="$file" || true
          done < linux-ia-files.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
