name: Upload Linux Distributables to Archive.org

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build and Release Electron App"]
    types:
      - completed

concurrency:
  group: IALINUX-${{ github.ref }}
  cancel-in-progress: true

jobs:
  upload-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Download all release assets
        id: download_linux
        uses: robinraju/release-downloader@v1.12
        with:
          latest: true
          fileName: "*"
          out-file-path: release-dist
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload distributables to archive.org
        uses: palewire/internet-archive-upload@v1
        with:
          access-key: ${{ secrets.IA_ACCESS_KEY }}
          secret-key: ${{ secrets.IA_SECRET_KEY }}
          identifier: fitfileviewer-linux-${{ steps.download_linux.outputs.tag_name }}
          files: release-dist/Fit-File-Viewer-linux-*.tar.bz2 release-dist/Fit-File-Viewer-linux-*.tar.gz release-dist/Fit-File-Viewer-linux-*.tar.xz release-dist/Fit-File-Viewer-linux-*.zip release-dist/Fit-File-Viewer-pacman-*.pacman release-dist/Fit-File-Viewer-rpm-*.rpm release-dist/Fit-File-Viewer-snap-*.snap release-dist/latest-linux.yml
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
