on:
  schedule:
    - cron: "28 2 * * *"
  workflow_dispatch:

jobs:
  upload-to-archive:
    runs-on: ubuntu-latest
    steps:
      - name: Check for new release in last 24 hours
        id: check_release
        run: |
          latest_release_time=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r '.published_at')
          if [ "$latest_release_time" = "null" ]; then
            echo "No releases found."
            echo "::set-output name=new_release::false"
            exit 0
          fi
          latest_release_epoch=$(date -d "$latest_release_time" +%s)
          now_epoch=$(date +%s)
          diff=$(( (now_epoch - latest_release_epoch) / 3600 ))
          if [ $diff -le 24 ]; then
            echo "::set-output name=new_release::true"
          else
            echo "::set-output name=new_release::false"
          fi
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload distributables to archive.org
        uses: palewire/internet-archive-upload@v1
        with:
          access-key: ${{ secrets.IA_ACCESS_KEY }}
          secret-key: ${{ secrets.IA_SECRET_KEY }}
          identifier: fitfileviewer-v${{ needs.bump-version.outputs.new_version }}
          files: release-dist/
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: steps.check_release.outputs.new_release == 'true'
