name: Upload macOS Distributables to Archive.org

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build and Release Electron App"]
    types:
      - completed

concurrency:
  group: IAMAC-${{ github.ref }}
  cancel-in-progress: true

jobs:
  upload-macos:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - name: Download macOS release assets (darwin-)
        id: download_darwin
        uses: robinraju/release-downloader@daf26c55d821e836577a15f77d86ddc078948b05 # v1.12
        with:
          latest: true
          fileName: "Fit-File-Viewer-darwin-*"
          out-file-path: release-dist
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download macOS release assets (dmg-)
        id: download_dmg
        uses: robinraju/release-downloader@daf26c55d821e836577a15f77d86ddc078948b05 # v1.12
        with:
          latest: true
          fileName: "Fit-File-Viewer-dmg-*"
          out-file-path: release-dist
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download macOS release assets (pkg-)
        id: download_pkg
        uses: robinraju/release-downloader@daf26c55d821e836577a15f77d86ddc078948b05 # v1.12
        with:
          latest: true
          fileName: "Fit-File-Viewer-pkg-*"
          out-file-path: release-dist
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download macOS release assets (latest-mac.yml)
        id: download_latest
        uses: robinraju/release-downloader@daf26c55d821e836577a15f77d86ddc078948b05 # v1.12
        with:
          latest: true
          fileName: "latest-mac.yml"
          out-file-path: release-dist
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload macOS distributables to archive.org
        uses: Nick2bad4u/internet-archive-upload@v1.3 # v1.3
        with:
          access-key: ${{ secrets.IA_ACCESS_KEY }}
          secret-key: ${{ secrets.IA_SECRET_KEY }}
          identifier: fitfileviewer-macos-${{ steps.download_darwin.outputs.tag_name }}
          files: release-dist/
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
