name: Upload Windows Distributables to Archive.org

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build and Release Electron App"]
    types:
      - completed

concurrency:
  group: IAWINDOWS-${{ github.ref }}
  cancel-in-progress: false

jobs:
  upload-windows:
    runs-on: windows-latest
    steps:
      - name: Download all Windows release assets
        id: download_windows
        uses: robinraju/release-downloader@v1.12
        with:
          latest: true
          fileName: |
            Fit-File-Viewer-msi-*.7z
            Fit-File-Viewer-msi-*.msi
            Fit-File-Viewer-msi-*.tar.bz2
            Fit-File-Viewer-msi-*.tar.gz
            Fit-File-Viewer-msi-*.tar.xz
            Fit-File-Viewer-msi-*.zip
            Fit-File-Viewer-nsis-*.exe
            Fit-File-Viewer-nsis-*.exe.blockmap
            Fit-File-Viewer-portable-*.exe
            latest.yml
          out-file-path: release-dist
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if version already uploaded
        id: check_version
        run: |
          VERSION="${{ steps.download_windows.outputs.tag_name }}"
          IDENTIFIER="fitfileviewer-windows-$VERSION"
          if curl --silent --fail "https://archive.org/metadata/$IDENTIFIER" > /dev/null; then
            echo "Version already uploaded. Skipping."
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi

      - name: Upload distributables to archive.org
        if: steps.check_version.outputs.skip != 'true'
        uses: palewire/internet-archive-upload@v1
        with:
          access-key: ${{ secrets.IA_ACCESS_KEY }}
          secret-key: ${{ secrets.IA_SECRET_KEY }}
          identifier: fitfileviewer-windows-${{ steps.download_windows.outputs.tag_name }}
          files: release-dist/
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
