name: Upload macOS Distributables to Archive.org

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build and Release Electron App"]
    types:
      - completed

concurrency:
  group: IAMAC-${{ github.ref }}
  cancel-in-progress: true

jobs:
  upload-macos:
    runs-on: ubuntu-latest
    steps:
      - name: Download all release assets
        id: download_macos
        uses: robinraju/release-downloader@v1.12
        with:
          latest: true
          fileName: "*"
          out-file-path: release-dist
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: List all macOS distributables
        id: list_files
        run: |
          files=()
          for pattern in \
            "release-dist/Fit-File-Viewer-mac-*.dmg" \
            "release-dist/Fit-File-Viewer-mac-*.zip" \
            "release-dist/Fit-File-Viewer-macos-*.dmg" \
            "release-dist/Fit-File-Viewer-macos-*.zip" \
            "release-dist/latest-mac.yml"
          do
            for f in $pattern; do
              [ -e "$f" ] && files+=("$f")
            done
          done
          printf '%s\n' "${files[@]}" > macos-ia-files.txt

      - name: Upload each distributable to archive.org
        run: |
          set -e
          while IFS= read -r file; do
            echo "Uploading $file to archive.org..."
            gh workflow run palewire/internet-archive-upload@v1 \
              --with access-key=${{ secrets.IA_ACCESS_KEY }} \
              --with secret-key=${{ secrets.IA_SECRET_KEY }} \
              --with identifier=fitfileviewer-macos-${{ steps.download_macos.outputs.tag_name }} \
              --with files="$file" || true
          done < macos-ia-files.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
