name: Upload macOS Distributables to Archive.org

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build and Release Electron App"]
    types:
      - completed

concurrency:
  group: IAMAC-${{ github.ref }}
  cancel-in-progress: true

jobs:
  upload-macos:
    runs-on: ubuntu-latest
    steps:
      - name: Download all release assets
        id: download_macos
        uses: robinraju/release-downloader@v1.12
        with:
          latest: true
          fileName: "*"
          out-file-path: release-dist
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload distributables to archive.org
        uses: palewire/internet-archive-upload@v1
        with:
          access-key: ${{ secrets.IA_ACCESS_KEY }}
          secret-key: ${{ secrets.IA_SECRET_KEY }}
          identifier: fitfileviewer-macos-${{ steps.download_macos.outputs.tag_name }}
          files: release-dist/Fit-File-Viewer-mac-*.dmg release-dist/Fit-File-Viewer-mac-*.zip release-dist/Fit-File-Viewer-macos-*.dmg release-dist/Fit-File-Viewer-macos-*.zip release-dist/latest-mac.yml
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
