name: Upload macOS Distributables to Archive.org

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build and Release Electron App"]
    types:
      - completed

concurrency:
  group: IAMAC-${{ github.ref }}
  cancel-in-progress: false

jobs:
  upload-macos:
    runs-on: macos-latest
    steps:
      - name: Download all macOS release assets
        id: download_macos
        uses: robinraju/release-downloader@v1.12
        with:
          latest: true
          fileName: |
            Fit-File-Viewer-darwin-*.tar.bz2
            Fit-File-Viewer-darwin-*.tar.gz
            Fit-File-Viewer-darwin-*.tar.xz
            Fit-File-Viewer-darwin-*.zip
            Fit-File-Viewer-darwin-*.zip.blockmap
            Fit-File-Viewer-dmg-*.dmg
            Fit-File-Viewer-dmg-*.dmg.blockmap
            Fit-File-Viewer-pkg-*.pkg
            latest-mac.yml
          out-file-path: release-dist
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if version already uploaded
        id: check_version
        run: |
          VERSION="${{ steps.download_macos.outputs.tag_name }}"
          IDENTIFIER="fitfileviewer-macos-$VERSION"
          if curl --silent --fail "https://archive.org/metadata/$IDENTIFIER" > /dev/null; then
            echo "Version already uploaded. Skipping."
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi

      - name: Upload distributables to archive.org
        if: steps.check_version.outputs.skip != 'true'
        uses: palewire/internet-archive-upload@v1
        with:
          access-key: ${{ secrets.IA_ACCESS_KEY }}
          secret-key: ${{ secrets.IA_SECRET_KEY }}
          identifier: fitfileviewer-macos-${{ steps.download_macos.outputs.tag_name }}
          files: release-dist/
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
