name: Upload Windows Distributables to Archive.org

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build and Release Electron App"]
    types:
      - completed

concurrency:
  group: IAWINDOWS-${{ github.ref }}
  cancel-in-progress: true

jobs:
  upload-windows:
    runs-on: ubuntu-latest
    steps:
      - name: Download all release assets
        id: download_windows
        uses: robinraju/release-downloader@v1.12
        with:
          latest: true
          fileName: "*"
          out-file-path: release-dist
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload distributables to archive.org
        uses: palewire/internet-archive-upload@v1
        with:
          access-key: ${{ secrets.IA_ACCESS_KEY }}
          secret-key: ${{ secrets.IA_SECRET_KEY }}
          identifier: fitfileviewer-windows-${{ steps.download_windows.outputs.tag_name }}
          files: release-dist/Fit-File-Viewer-win32-*.exe release-dist/Fit-File-Viewer-win32-*.msi release-dist/Fit-File-Viewer-windows-*.exe release-dist/Fit-File-Viewer-windows-*.msi release-dist/Fit-File-Viewer-windows-*.zip release-dist/latest-windows.yml
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
