name: Upload macOS Distributables to Archive.org

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build and Release Electron App"]
    types:
      - completed

concurrency:
  group: IAMAC-${{ github.ref }}
  cancel-in-progress: true

jobs:
  upload-macos:
    runs-on: ubuntu-latest
    steps:
      - name: Download macOS release assets (mac-)
        id: download_mac
        uses: robinraju/release-downloader@v1.12
        with:
          latest: true
          fileName: "Fit-File-Viewer-mac-*"
          out-file-path: release-dist
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download macOS release assets (macos-)
        id: download_macos
        uses: robinraju/release-downloader@v1.12
        with:
          latest: true
          fileName: "Fit-File-Viewer-macos-*"
          out-file-path: release-dist
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download macOS release assets (latest-mac.yml)
        id: download_latest
        uses: robinraju/release-downloader@v1.12
        with:
          latest: true
          fileName: "latest-mac.yml"
          out-file-path: release-dist
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload macOS distributables to archive.org
        uses: palewire/internet-archive-upload@v1
        with:
          access-key: ${{ secrets.IA_ACCESS_KEY }}
          secret-key: ${{ secrets.IA_SECRET_KEY }}
          identifier: fitfileviewer-macos-${{ steps.download_macos.outputs.tag_name }}
          files: release-dist/
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
