# VSCode Version Matrix - GitHub Action
# Retrieves Electron, Node, and Chromium versions for a given VSCode version

name: VSCode Version Matrix

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: vscode-version-${{ github.ref }}
  cancel-in-progress: false

jobs:
  vscode-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Retrieve VSCode dependency versions
        id: vscode-versions
        uses: EcksDy/vscode-version-matrix@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: 1.82.0
      - name: Print Output
        run: |
          echo "vscode-version-name = ${{ steps.vscode-versions.outputs.vscode-version-name }}"
          echo "vscode-version = ${{ steps.vscode-versions.outputs.vscode-version }}"
          echo "released-at = ${{ steps.vscode-versions.outputs.released-at }}"
          echo "electron-version = ${{ steps.vscode-versions.outputs.electron-version }}"
          echo "node-version = ${{ steps.vscode-versions.outputs.node-version }}"
          echo "chromium-version = ${{ steps.vscode-versions.outputs.chromium-version }}"
